apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: django
  name: djangobuild
spec:
  replicas: 2
  selector:
    matchLabels:
      app: djangobuild
  template:
    metadata:
      labels:
        app: djangobuild
    spec:
      containers:
        - name: deploy2
          image: eunicesooyoung/dockerfile:v2
          envForm:
          - secretRef:
              name: dj-sec
          ports:
            - containerPort: 8000
      restartPolicy: Always
