apiVersion: v1
kind: Service
metadata:
  namespace: django
  name: djangobuild
spec:
  type: LoadBalancer
  selector:
    app: djangobuild
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
